spring.application.name=JournalApp
server.port=8080

# SQL Server configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Journal_App;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Supanta@1247
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# JDBC logging (optional but useful for learning)
spring.jdbc.template.query-timeout=30
spring.jpa.open-in-view=false
jwt.secret=TaK+TaSE3W9tXm9zWE90S2V5U3VwYW50YURhc0pvdXJuYWxBcHA=
jwt.expiration=36000000